version: "3.9"
services:
  rustapptest:
    container_name: RustAppTest
    build:
      context: ../main/
      dockerfile: ../docker_rustapp/Dockerfile
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ../main:/app/
    command: sh -c "diesel migration run && cargo test"
    environment:
      - DATABASE_URL=postgres://testUser:testPassword@PostgresTestDb/rustapptest
    depends_on:
      - test-db
    networks:
      - rustapp-test-network
  test-db:
    container_name: PostgresTestDb
    image: postgres
    environment:
      - POSTGRES_USER=testUser
      - POSTGRES_PASSWORD=testPassword
      - POSTGRES_DB=rustapptest
    networks:
      - rustapp-test-network
networks:
  rustapp-test-network:
    driver: bridge
