version: "3.9"
services:
  rust-main-test:
    container_name: RustMainTest
    build:
      context: ../main/
      dockerfile: ../docker_rustapp/Dockerfile
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ../main:/app/
    command: sh -c "diesel migration run && cargo test"
    environment:
      - DATABASE_URL=postgres://testUser:testPassword@PostgresTestDb/rustmaintest
    depends_on:
      - test-db
    networks:
      - rustapp-test-network
  test-db:
    container_name: PostgresTestDb
    image: postgres
    environment:
      - POSTGRES_USER=testUser
      - POSTGRES_PASSWORD=testPassword
      - POSTGRES_DB=rustmaintest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testUser -d rustmaintest"]
      interval: 5s
      timeout: 4s
      retries: 5
    networks:
      - rustapp-test-network
networks:
  rustapp-test-network:
    driver: bridge
