version: "3.9"
services:
  main-test:
    container_name: MainServiceTest
    build:
      context: ../main/
      dockerfile: ../docker_rustapp/Dockerfile
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ../main:/app/
      - /app/target
      - ./wait_for_db.sh:/utils/wait_for_db.sh
    command: sh -c "/utils/wait_for_db.sh MainServiceTestDb 5432 && /utils/wait_for_db.sh ProductsServiceTest 5001 && diesel migration run && cargo test"
    environment:
      - DATABASE_URL=postgres://testUser:testPassword@MainServiceTestDb/rustmaintest
      - PRODUCTS_URL=http://ProductsServiceTest:5001/products
    depends_on:
      - main-test-db
    networks:
      - rustapp-test-network
  main-test-db:
    container_name: MainServiceTestDb
    image: postgres
    environment:
      - POSTGRES_USER=testUser
      - POSTGRES_PASSWORD=testPassword
      - POSTGRES_DB=rustmaintest
    networks:
      - rustapp-test-network
  # products service
  products-service-test:
    container_name: ProductsServiceTest
    build:
      context: ../products/
      dockerfile: ../docker_rustapp/Dockerfile
    ports:
      - 5001:5001
    working_dir: /app
    volumes:
      - ../products:/app/
      - /app/target
      - ./wait_for_db.sh:/utils/wait_for_db.sh
    command: sh -c "/utils/wait_for_db.sh ProductsServiceTestDb 5432 && diesel migration run && cargo run"
    environment:
      - DATABASE_URL=postgres://testUser:testPassword@ProductsServiceTestDb/rustproductstest
    depends_on:
      - test-db
    networks:
      - rustapp-test-network
  test-db:
    container_name: ProductsServiceTestDb
    image: postgres
    environment:
      - POSTGRES_USER=testUser
      - POSTGRES_PASSWORD=testPassword
      - POSTGRES_DB=rustproductstest
    networks:
      - rustapp-test-network
networks:
  rustapp-test-network:
    driver: bridge
